# -*- coding: utf-8 -*-
"""assignment5.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nyh3pKnstgevflqgLbJsxNDQBtZa94G_
"""

# Ask for user's address
address = input("What is your address? ")

# Print a greeting with the address
print(f"Hello, I will arrive shortly at: {address}!")